apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - image: jwfeb05/jw-home-api-gateway:latest
          imagePullPolicy: Always
          name: api-gateway
          ports:
            - containerPort: 9090
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: api-gateway
  name: api-gateway
  namespace: default
spec:
  ports:
    - port: 9090 #CHANGE
      name: http-traffic
      protocol: TCP
      targetPort: 9090 #CHANGE
  selector:
    app: api-gateway
  sessionAffinity: None #CHANGE
#  type: NodePort
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-monitor
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"